import 'package:pibro/internalization/app_strings.dart';

class EnglishStrings {
  static Map<String, String> getStrings() {
    return {
      // Main screen
      AppStrings.home: 'Home',
      AppStrings.profile: 'Profile',
      AppStrings.support: 'Support',

      // Landing screen
      AppStrings.pibl: 'POWER INSURANCE BROKERS\nLTD.',
      AppStrings.piblSubtitle: 'Insurance at your convenience',
      AppStrings.welcomeText:
          'Welcome to\nPower Insurance Brokerage\nSelf Service',
      AppStrings.explore: 'Explore',
      AppStrings.getQuote: 'Get Quote',

      // Login Screen
      AppStrings.welcomeBack: 'Welcome\nBack!',
      AppStrings.hello: 'Hello!',
      AppStrings.login: 'Login',
      AppStrings.rememberMe: 'Remember Me',
      AppStrings.forgotPassword: 'Forgot/Reset Password?',
      AppStrings.otherLoginOptions: 'Other Login Options',
      AppStrings.dontHaveAccount: 'Don\'t have an account?',
      AppStrings.alreadyHaveAccount: 'Already have an account?',
      AppStrings.signUp: 'Sign Up',
      AppStrings.username: 'Username',
      AppStrings.password: 'Password',
      AppStrings.email: 'Email',
      AppStrings.phoneNumber: 'Phone number',

      // Home Screen
      AppStrings.welcomeUser: 'Welcome,\n@user',
      AppStrings.activePolicies: 'Active@breakPolicies',
      AppStrings.expiredPolicies: 'Expired@breakPolicies',
      AppStrings.quote: 'Quote',
      AppStrings.quoteId: 'Quote ID',
      AppStrings.quotes: 'Quotes',
      AppStrings.renewPolicy: 'Renew Policy',
      AppStrings.lodgeClaims: 'Lodge Claims',
      AppStrings.policies: 'Policies',

      // Support
      AppStrings.contactUs: 'Contact Us',
      AppStrings.faq: 'FAQ',
      AppStrings.chat: 'Chat',

      // Profile
      AppStrings.myInfo: 'My Info',
      AppStrings.accountHandler: 'Account Handler',
      AppStrings.notification: 'Notification',
      AppStrings.configuration: 'Configuration',
      AppStrings.changePassword: 'Change Password',
      AppStrings.logout: 'Log Out',
      AppStrings.name: 'Name',
      AppStrings.dob: 'Date of Birth',
      AppStrings.accountType: 'Account Type',
      AppStrings.individual: 'Individual',
      AppStrings.company: 'Company',
      AppStrings.jointAccount: 'Joint Account',
      AppStrings.companyName: 'Company Name',
      AppStrings.accountName: 'Account Name',
      AppStrings.dateOfIncorporation: 'Date of Incorporation',
      AppStrings.primaryHolderDob: 'Primary Holder\'s Date of Birth',
      AppStrings.country: 'Country',
      AppStrings.state: 'State',
      AppStrings.address: 'Address',
      AppStrings.logoutConfirmation: 'Are you sure you want to\nlog out?',
      AppStrings.cancel: 'Cancel',
      AppStrings.sms: 'SMS',
      AppStrings.save: 'Save',
      AppStrings.oldPassword: 'Old Password',
      AppStrings.newPassword: 'New Password',
      AppStrings.confirmPassword: 'Confirm Password',
      AppStrings.ok: 'OK',
      AppStrings.changePasswordSuccess: 'Password changed successfully',
      AppStrings.enterServiceUrl: 'Enter Service URL',
      AppStrings.enterToken: 'Enter Token',
      AppStrings.scanQR: 'Scan QR Code',

      // Api
      AppStrings.genericErrorMessage:
          'There has been an error. Please retry later.',
      AppStrings.inputFieldRequired: '@field is required',
      AppStrings.inputFieldInvalid: '@field is invalid',

      // Policy
      AppStrings.policyDetail: 'Policy Detail',
      AppStrings.quoteDetail: 'Quote Detail',
      AppStrings.policyNumber: 'Policy Number',
      AppStrings.policySummary: 'Policy Summary',
      AppStrings.insuranceClass: 'Insurance Class',
      AppStrings.product: 'Product',
      AppStrings.startDate: 'Start Date',
      AppStrings.oldStartDate: 'Old Start Date',
      AppStrings.newStartDate: 'New Start Date',
      AppStrings.endDate: 'End Date',
      AppStrings.oldEndDate: 'Old End Date',
      AppStrings.newEndDate: 'New End Date',
      AppStrings.renewalDate: 'Renewal Date',
      AppStrings.newRenewalDate: 'New Renewal Date',
      AppStrings.sumInsured: 'Sum Insured',
      AppStrings.premium: 'Premium',
      AppStrings.premiumDue: 'Premium Due',
      AppStrings.status: 'Status',
      AppStrings.itemInsured: 'Item Insured',
      AppStrings.description: 'Description',
      AppStrings.location: 'Location',
      AppStrings.value: 'Value',
      AppStrings.next: 'Next',
      AppStrings.renew: 'Renew',
      AppStrings.endorse: 'Endorse',
      AppStrings.claim: 'Claim',
      AppStrings.pending: 'Pending',
      AppStrings.active: 'Active',
      AppStrings.expired: 'Expired',
      AppStrings.renewPolicyPreference: 'Renew Policy Preference',
      AppStrings.continueText: 'Continue',
      AppStrings.makePayment: 'Make Payment',
      AppStrings.paymentConfirmation: 'Payment Confirmation',
      AppStrings.paymentDate: 'Payment Date',
      AppStrings.paymentReference: 'Payment Reference',
      AppStrings.paymentMethod: 'Payment Method',
      AppStrings.submitQuoteForApproval: 'Submit Quote For Approval',
      AppStrings.itemToInsure: 'Item To Insure',
      AppStrings.regNo: 'Reg. No',
      AppStrings.regId: 'Registration ID',
      AppStrings.chasisId: 'Chasis ID',
      AppStrings.engineNo: 'Engine No',
      AppStrings.vehicleMake: 'Vehicle Make',
      AppStrings.submit: 'Submit',
      AppStrings.view: 'View',
      AppStrings.insurer: 'Insurer',
      AppStrings.apportionment: 'Apportionment',
      AppStrings.noData: 'No Data',
      AppStrings.renewPolicySuccess: 'Renew Policy Request Sent to Broker',
      AppStrings.payWithPaystack: 'Pay with Paystack',
      AppStrings.print: 'Print',
      AppStrings.congratulations: 'Congratulations',
      AppStrings.paymentSuccess:
          'Your payment has been successfully processed and your policy',
      AppStrings.paymentSuccessNowActive: 'is now active',
      AppStrings.detailsBelow: 'Find below the details of the transaction',

      // Quote
      AppStrings.lifeInsurance: 'Life\nInsurance',
      AppStrings.nonLifeInsurance: 'Non-Life\nInsurance',
      AppStrings.reInsurance: 'Re-Insurance',
      AppStrings.policyQuoteSent: 'Policy Quote Sent',
      AppStrings.policyQuoteSentToBroker: 'Policy Quote Request Sent To Broker',

      // Claim
      AppStrings.claims: 'Claims',
      AppStrings.claimDetails: 'Claim Details',
      AppStrings.claimNumber: 'Claim Number',
      AppStrings.incidentDate: 'Incident Date',
      AppStrings.claimReportedDate: 'Claim Reported Date',
      AppStrings.claimAmount: 'Claim Amount',
      AppStrings.settlementAmount: 'Settlement Amount',
      AppStrings.dateOfOccurence: 'Date of Occurence',
      AppStrings.narration: 'Narration',
      AppStrings.leadInsurer: 'Lead Insurer',
      AppStrings.policyHolder: 'Policy Holder',
      AppStrings.typesOfBusiness: 'Types of Business',
      AppStrings.sendToBroker: 'Send to Broker',
      AppStrings.saveAndContinue: 'Save and Continue',
      AppStrings.submitClaim: 'Submit Claim',
      AppStrings.claimSuccess: 'Claim Successfully Submited to Broker',
      AppStrings.main: 'Main',
      AppStrings.claimDocument: 'Claim Document(s)',
      AppStrings.insurers: 'Insurer(s)',
      AppStrings.uploadClaimDocuments: 'Upload Claim Documents',
      AppStrings.uploadDocuments: 'Upload Documents',
      AppStrings.policeReport: 'Police Report',
      AppStrings.photographOfIncident: 'Photograph of Incident',
      AppStrings.upload: 'Upload',
      AppStrings.updateDocuments: 'Update Documents',
      AppStrings.submitted: 'Submitted',
      AppStrings.notSubmitted: 'Not Submitted',
      AppStrings.date: 'Date',
      AppStrings.total: 'Total',
      AppStrings.amountPaid: 'Amount Paid',
      AppStrings.balanceDue: 'Balance Due',
      AppStrings.browseFiles: 'Browse Files',
      AppStrings.update: 'Update',
      AppStrings.close: 'Close',
      AppStrings.added: 'Added',
      AppStrings.edit: 'Edit',
      AppStrings.settled: 'Settled',
      AppStrings.processing: 'Processing',
      AppStrings.preview: 'Preview',
      AppStrings.addImage: 'Add Image',

      // Configuration
      AppStrings.configError:
          'Configuration data is not set. Please set the service URL and token.',
      AppStrings.configIncorrect:
          'Configuration data is incorrect. Please set the correct service URL and token.',
      AppStrings.insuranceCertificate: 'Insurance Certificate',
      AppStrings.insuranceCertificateSaved: 'Insurance certificate saved to:',
    };
  }
}
